server/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('login', views.LoginView.as_view(), name = 'Login'),
    path('register', views.SignupView.as_view(), name = 'Signup'),
    path('forgot', views.ForgotView.as_view(), name = 'Forgot'),
    path('reset', views.PasswordResetView.as_view(), name = 'Reset'),

]

server/buses/urls.py
from django.urls import path
from . import views

app_name = 'buses'

urlpatterns = [

    path('buses', views.BusSearchView.as_view(), name = 'Search'),
    path('buses/list', views.BusDisplayView.as_view(), name = 'Display'),
    path('buses/view/<slug:id>', views.BusDetailsView.as_view(), name = 'Details'),
    path('buses/bookings/<slug:id>', views.BusBookingListView.as_view(), name = 'Bookings'),

]

server/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [

    path('dashboard', views.DashboardView.as_view(), name = 'Dashboard'),
    path('manage', views.AdminView.as_view(), name = 'Admin'),
    path('logout', views.LogoutView.as_view(), name = 'Logout'),
    path('services', views.ServiceView.as_view(), name = 'Services'),
    path('service/<slug:id>', views.EditServiceView.as_view(), name = 'EditService'),
    path('delete_manager_from_service/<slug:id>/<slug:email>', views.DeleteManagerView.as_view(), name = 'DeleteManager'),
    path('delete_bus_route/<slug:id>/<int:index>', views.DeleteRouteView.as_view(), name = 'DeleteBusRoute'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('person.urls')),
    path('', include('hotels.urls')),
    path('booking/', include('booking.urls')),
    path('', include('buses.urls')),
]

server/accounts/models.py
from django.db import models

server/accounts/forms.py
from django import forms
from database import models
from django.core import validators

class LoginForm(forms.Form):
    email = forms.EmailField(max_length = 100, required = True)
    password = forms.CharField(max_length = 100, required = True)

class SignupForm(forms.Form):
    email = forms.EmailField(max_length = 100, required = True)
    password = forms.CharField(max_length = 100, required = True)
    password_cnf = forms.CharField(max_length = 100, required = True)

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            v = validators.validate_email(email)
        except:
            raise forms.ValidationError("Enter a valid email address")

        try:
            user = self.get_object(email)
            if user.count() > 0:
                raise forms.ValidationError("User already exists")
            else:
                return email
        except Exception as e:
            raise e

    def clean_password_cnf(self):
        pass1 = self.cleaned_data['password']
        pass2 = self.cleaned_data['password_cnf']
        if len(pass1) == 0 or len(pass2) == 0:
            raise forms.ValidationError("Fields cannot be empty")
        elif pass1 != pass2:
            raise forms.ValidationError("Passwords do not match")
        else:
            return pass1

class ForgotForm(forms.Form):
    email = forms.EmailField(max_length = 100, required = True)

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def clean_email(self):
        email = self.cleaned_data['email']
        user = self.get_object(email)
        if user.count() > 0:
            return email
        else:
            raise forms.ValidationError("Email not registered")

class PasswordResetForm(forms.Form):
    password = forms.CharField(max_length = 100, required = True)
    password_cnf = forms.CharField(max_length = 100, required = True)

    def clean_password_cnf(self):
        pass1 = self.cleaned_data['password']
        pass2 = self.cleaned_data['password_cnf']
        if len(pass1) == 0 or len(pass2) == 0:
            raise forms.ValidationError("Fields cannot be empty")
        elif pass1 != pass2:
            raise forms.ValidationError("Passwords do not match")
        else:
            return pass1

server/accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.hashers import make_password, check_password
from django.utils.crypto import get_random_string
from database import models
from . import forms
from database import utils
from . import mail

class LoginView(View):
    template_name = 'accounts/login.html'

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def get(self, request):
        return render(request, self.template_name, {'form': forms.LoginForm()})

    def post(self, request):
        try:
            user = self.get_object(request.POST['email'])
            if user.count() == 0:
                return render(request, self.template_name, {'form': forms.LoginForm(), 'error': '1', 'msg': 'User does not exist. SignUp to proceed'})
            else:
                user = user[0]
                r = utils.get_user_rep(user)
                pass2 = r.get('password')
                if check_password(request.POST['password'], pass2) == True:
                    request.session.update({'email': user.email, 'type': r.get('type')})
                    return redirect('person:Dashboard')
                else:
                    return render(request, self.template_name, {'form': forms.LoginForm(), 'error': '1', 'msg': 'Incorrect Password'})
        except:
            return render(request, self.template_name, {'form': forms.LoginForm(), 'error': '1', 'msg': 'Internal Error'})

class SignupView(View):
    template_name = 'accounts/signup.html'

    def get(self, request):
        return render(request, self.template_name, {'form': forms.SignupForm()})

    def post(self, request):
        try:
            form = forms.SignupForm(request.POST)
            if form.is_valid():
                token = make_password(get_random_string(length = 16))
                password = make_password(form.cleaned_data['password'])
                r = utils.insert_user(form.cleaned_data['email'], password, token, 'U')
                if r == 201:
                    return render(request, self.template_name, {'form': forms.SignupForm(), 'success': '1', 'msg': 'Account created Successfully'})
                else:
                    return render(request, self.template_name, {'form': forms.SignupForm(), 'error': '1', 'msg': 'Network error. Try later.'})
            else:
                return render(request, self.template_name, {'form': form, 'error': '1', 'form_err': '1'})
        except Exception as e:
            return render(request, self.template_name, {'form': forms.SignupForm(), 'error': '1', 'msg': 'Incorrect Submission'})

class ForgotView(View):
    template_name = 'accounts/forgot.html'

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def get(self, request):
        return render(request, self.template_name, {'form': forms.ForgotForm()})

    def post(self, request):
        form = forms.ForgotForm(request.POST)
        if form.is_valid():
            user = self.get_object(form.cleaned_data['email'])
            user = user[0]
            token = get_random_string(length = 16)
            r = utils.update_user(user.db_name, user.email, token = make_password(token))
            if r == 200:
                mail.sendUserForgotMail(user.email, token)
                return render(request, self.template_name, {'form': forms.ForgotForm(), 'success': '1', 'msg': 'Please check your email for further instructions'})
            else:
                return render(request, self.template_name, {'form': forms.ForgotForm(), 'error': '1', 'msg': 'Network Error. Please try again later.'})
        else:
            return render(request, self.template_name, {'form': forms.ForgotForm(), 'error': '1', 'msg': 'Email is not registered'})

class PasswordResetView(View):
    template_name = 'accounts/reset.html'

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def get(self, request):
        user = self.get_object(request.GET.get('id'))
        if user.count() > 0:
            user = user[0]
            r = utils.get_user_rep(user)
            if check_password(request.GET.get('token'), r.get('token')) == True:
                return render(request, self.template_name, {'form': forms.PasswordResetForm()})
            else:
                print('PAGE NOT FOUND')
        else:
            print('PAGE NOT FOUND')

    def post(self, request):
        form = forms.PasswordResetForm(request.POST)
        if form.is_valid():
            user = self.get_object(request.GET.get('id'))[0]
            token = make_password(get_random_string(length = 16))
            password = make_password(form.cleaned_data['password'])
            r = utils.update_user(user.db_name, user.email, token = token, password = password)
            if r == 200:
                return render(request, 'accounts/reset_done.html')
            else:
                return render(request, self.template_name, {'form': form, 'error': '1', 'msg': 'Network Error. Please try again later'})
        else:
            return render(request, self.template_name, {'form': form, 'form_err': '1'})

server/accounts/templates/accounts/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title_block %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  </head>
  <body>
      <!-- NAVBAR -->
      <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
          <div class="container">
              <div class="navbar-brand">
                  <a class="navbar-item" href="{% url 'person:Dashboard' %}">
                      <p style="font-size: 22px;">Easy<span style="color: green;">Travels</span></p>
                  </a>
                  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                  </a>
              </div>
              <div id="navbarBasicExample" class="navbar-menu">
                  <div class="navbar-start">
                      <div class="navbar-item" style="margin-left: 250%;">
                          <div class="title is-4">Travel Agency</div>
                      </div>
                  </div>
                  <div class="navbar-end">
                      <div class="navbar-item">
                          <div class="buttons">
                              <a href="{% url 'accounts:Signup' %}" class="button is-primary is-medium">Sign up</a>
                              <a href="{% url 'accounts:Login' %}" class="button is-primary is-medium">Log in</a>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
     </nav>
     <!-- NAVBAR END -->
     <section class="hero is-light is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                {% block form_block %}{% endblock %}
            </div>
        </div>
    </section>
  </body>
</html>

server/accounts/templates/accounts/forgot.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}

{% block title_block %}Forgot{% endblock %}

{% block form_block %}

    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Retrieve Account</h3>
        <p class="subtitle has-text-grey">Enter your email address</p>
        <div class="box">
            <form method = "POST">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        {% render_field form.email type="text" class="input is-medium" placeholder="Your Email" %}
                    </div>
                </div>
                <button class="button is-fullwidth is-info is-medium">Submit</button>
            </form>
        </div>
        <div class="content">
            <a class="tag is-medium is-light" href="{% url 'accounts:Login' %}"><strong>Login</strong></a> &nbsp;·&nbsp;
            <a class="tag is-light is-medium" href="{% url 'accounts:Signup' %}"><strong>Sign Up</strong></a> &nbsp;·&nbsp;
        </div>
        <!-- MESSAGES -->
        <div>
            {% if error %}
            <div class="content">
                <span style="color: red;">{{ msg }}</span>
            </div>
            {% endif %}
            {% if form_err %}
                {% for field in form %}
                    {% if field.errors %}
                    <div class="content"><span style="color: red;">{{ field.errors | striptags }}</span></div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if success %}
                <div class="content"><span style="color: blue;">{{ msg }}</span></div>
            {% endif %}
        </div>
        <!-- MESSAGES END -->
    </div>

{% endblock %}

server/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}

{% block title_block %}Login{% endblock %}

{% block form_block %}

    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Login</h3>
        <p class="subtitle has-text-grey">Please login to proceed.</p>
        <div class="box">
            <form method = "POST">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        {% render_field form.email type="text" class="input is-medium" placeholder="Your Email" %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {% render_field form.password type="password" class="input is-medium" placeholder="Your Password" %}
                    </div>
                </div>
                <button class="button is-fullwidth is-info is-medium">Login</button>
            </form>
        </div>
        <div class="content">
            <a class="tag is-medium is-light" href="{% url 'accounts:Signup' %}"><strong>Sign Up</strong></a> &nbsp;·&nbsp;
            <a class="tag is-light is-medium" href="{% url 'accounts:Forgot' %}"><strong>Forgot Password</strong></a> &nbsp;·&nbsp;
        </div>
        <!-- MESSAGES -->
        <div>
            {% if error %}
            <div class="content">
                <span style="color: red;">{{ msg }}</span>
            </div>
            {% endif %}
        </div>
        <!-- MESSAGES END -->
    </div>

{% endblock %}

server/accounts/templates/accounts/reset.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}

{% block title_block %}Forgot{% endblock %}

{% block form_block %}

    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Retrieve Account</h3>
        <p class="subtitle has-text-grey">Enter your email address</p>
        <div class="box">
            <form method = "POST">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        {% render_field form.password type="password" class="input is-medium" placeholder="Password" %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {% render_field form.password_cnf type="password" class="input is-medium" placeholder="Confirm Password" %}
                    </div>
                </div>
                <button class="button is-fullwidth is-info is-medium">Submit</button>
            </form>
        </div>
        <div class="content">
            <a class="tag is-medium is-light" href="{% url 'accounts:Login' %}"><strong>Login</strong></a> &nbsp;·&nbsp;
            <a class="tag is-light is-medium" href="{% url 'accounts:Signup' %}"><strong>Sign Up</strong></a> &nbsp;·&nbsp;
        </div>
        <!-- MESSAGES -->
        <div>
            {% if error %}
            <div class="content">
                <span style="color: red;">{{ msg }}</span>
            </div>
            {% endif %}
            {% if form_err %}
                {% for field in form %}
                    {% if field.errors %}
                    <div class="content"><span style="color: red;">{{ field.errors | striptags }}</span></div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if success %}
                <div class="content"><span style="color: blue;">{{ msg }}</span></div>
            {% endif %}
        </div>
        <!-- MESSAGES END -->
    </div>

{% endblock %}

server/accounts/templates/accounts/reset_done.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}

{% block title_block %}Forgot{% endblock %}

{% block form_block %}

    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Password Changed</h3>
        <div class="box content">
            <div class="subtitle is-6" style="color: blue;">
                Your password has been changed. Login to proceed.
            </div>
        </div>
        <div class="content">
            <a class="tag is-medium is-info" href="{% url 'accounts:Login' %}"><strong>Login</strong></a>
        </div>
        <!-- MESSAGES -->

        <!-- MESSAGES END -->
    </div>

{% endblock %}

server/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}

{% block title_block %}Sign Up{% endblock %}

{% block form_block %}

    <div class="column is-4 is-offset-4">
        <h3 class="title has-text-grey">Sign Up</h3>
        <p class="subtitle has-text-grey">Register your account</p>
        <div class="box">
            <form method = "POST">
                {% csrf_token %}
                <div class="field">
                    <div class="control">
                        {% render_field form.email type="email" class="input is-medium" placeholder="Email" %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {% render_field form.password type="password" class="input is-medium" placeholder="Password" %}
                    </div>
                </div>
                <div class="field">
                    <div class="control">
                        {% render_field form.password_cnf type="password" class="input is-medium" placeholder="Confirm Password" %}
                    </div>
                </div>
                <button class="button is-fullwidth is-info is-medium">Register</button>
            </form>
        </div>
        <div class="content">
            <a class="tag is-medium is-light" href="{% url 'accounts:Login' %}"><strong>Login</strong></a> &nbsp;·&nbsp;
            <a class="tag is-light is-medium" href="{% url 'accounts:Forgot' %}"><strong>Forgot Password</strong></a> &nbsp;·&nbsp;
        </div>
        <!-- MESSAGES -->
        <div>
            {% if error %}
            <div class="content">
                <span style="color: red;">{{ msg }}</span>
            </div>
            {% endif %}
            {% if form_err %}
                {% for field in form %}
                    {% if field.errors %}
                    <div class="content"><span style="color: red;">{{ field.errors | striptags }}</span></div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if success %}
                <div class="content"><span style="color: green;">{{ msg }}</span></div>
            {% endif %}
        </div>
        <!-- MESSAGES END -->
    </div>

{% endblock %}