server/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [

    path('upcoming', views.UpcomingView.as_view(), name = 'Upcoming'),
    path('past', views.PastView.as_view(), name = 'Past'),
    path('view/<slug:id>', views.BookingDetailView.as_view(), name = 'Detail'),

]

server/buses/urls.py
from django.urls import path
from . import views

app_name = 'buses'

urlpatterns = [

    path('buses', views.BusSearchView.as_view(), name = 'Search'),
    path('buses/list', views.BusDisplayView.as_view(), name = 'Display'),
    path('buses/view/<slug:id>', views.BusDetailsView.as_view(), name = 'Details'),
    path('buses/bookings/<slug:id>', views.BusBookingListView.as_view(), name = 'Bookings'),

]

server/hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [

    path('hotels', views.HotelSearchView.as_view(), name = 'Search'),
    path('hotels/list', views.HotelDisplayView.as_view(), name = 'Display'),
    path('hotels/view/<slug:id>', views.HotelDetailsView.as_view(), name = 'Details'),
    path('hotels/bookings/<slug:id>', views.HotelBookingListView.as_view(), name = 'Bookings'),

]

server/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [

    path('dashboard', views.DashboardView.as_view(), name = 'Dashboard'),
    path('manage', views.AdminView.as_view(), name = 'Admin'),
    path('logout', views.LogoutView.as_view(), name = 'Logout'),
    path('services', views.ServiceView.as_view(), name = 'Services'),
    path('service/<slug:id>', views.EditServiceView.as_view(), name = 'EditService'),
    path('delete_manager_from_service/<slug:id>/<slug:email>', views.DeleteManagerView.as_view(), name = 'DeleteManager'),
    path('delete_bus_route/<slug:id>/<int:index>', views.DeleteRouteView.as_view(), name = 'DeleteBusRoute'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('person.urls')),
    path('', include('hotels.urls')),
    path('booking/', include('booking.urls')),
    path('', include('buses.urls')),
]

server/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title_block %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  </head>
  <body>
      <!-- NAVBAR -->
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
          <div class="container">
              <div class="navbar-brand">
                  <div class="navbar-item" href="{% url 'person:Dashboard' %}">
                      <p style="font-size: 22px;">Easy<span style="color: green;">Travels</span></p>
                  </div>
                  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                  </a>
              </div>
              <div id="navbarBasicExample" class="navbar-menu">
                  <div class="navbar-start">
                      <a class="navbar-item" href="{% url 'person:Dashboard' %}">
                          <p style="margin: 10px; font-size: 18px;">Dashboard</p>
                      </a>
                      <a class="navbar-item" href="{% url 'hotels:Search' %}">
                          <p style="margin: 10px; font-size: 18px;">Hotels</p>
                      </a>
                      <a class="navbar-item" href="{% url 'buses:Search' %}">
                          <p style="margin: 10px; font-size: 18px;">Buses</p>
                      </a>
                  </div>
                  <div class="navbar-end">
                      <a class="navbar-item" href="{% url 'person:Admin' %}" {% block admin_block %}{% endblock %}>
                          <p style="margin: 10px; font-size: 18px;">Admin</p>
                      </a>
                      <a class="navbar-item" href="{% url 'person:Services' %}" {% block service_block %}{% endblock %}>
                          <p style="margin: 10px; font-size: 18px;">Services</p>
                      </a>
                      <div class="dropdown navbar-item is-hoverable">
                          <div class="dropdown-trigger">
                              <a class="button is-medium is-inverted is-link is-rounded" aria-haspopup="true" aria-controls="dropdown-menu">
                                  <p style="font-size: 18px;">Account</p>
                              </a>
                          </div>
                          <div class="dropdown-menu" id="dropdown-menu" role="menu">
                              <div class="dropdown-content">
                                  <a class="dropdown-item" href="{% url 'booking:Upcoming' %}">
                                      <span class="subtitle is-6">Upcoming Trips</span>
                                  </a>
                                  <a class="dropdown-item" href="{% url 'booking:Past' %}">
                                      <span class="subtitle is-6">Past Trips</span>
                                  </a>
                                  <hr class="dropdown-divider">
                                  <a href="#" class="dropdown-item">
                                      <span class="subtitle is-6">Account Details</span>
                                  </a>
                                  <a href="{% url 'person:Logout' %}" class="dropdown-item">
                                      <span class="subtitle is-6">Logout</span>
                                  </a>
                              </div>
                          </div>
                        </div>
                  </div>
              </div>
          </div>
     </nav>

     <!-- NAVBAR END -->
     <section class="section">
         <div class="container">
             {% block content_block %}{% endblock %}
         </div>
     </section>

     <script>
        var dropdown = document.querySelector('.dropdown');
        dropdown.addEventListener('click', function(event) {
            event.stopPropagation();
            dropdown.classList.toggle('is-active');

        });
     </script>

  </body>
</html>