server/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [

    path('upcoming', views.UpcomingView.as_view(), name = 'Upcoming'),
    path('past', views.PastView.as_view(), name = 'Past'),
    path('view/<slug:id>', views.BookingDetailView.as_view(), name = 'Detail'),

]

server/buses/urls.py
from django.urls import path
from . import views

app_name = 'buses'

urlpatterns = [

    path('buses', views.BusSearchView.as_view(), name = 'Search'),
    path('buses/list', views.BusDisplayView.as_view(), name = 'Display'),
    path('buses/view/<slug:id>', views.BusDetailsView.as_view(), name = 'Details'),
    path('buses/bookings/<slug:id>', views.BusBookingListView.as_view(), name = 'Bookings'),

]

server/hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [

    path('hotels', views.HotelSearchView.as_view(), name = 'Search'),
    path('hotels/list', views.HotelDisplayView.as_view(), name = 'Display'),
    path('hotels/view/<slug:id>', views.HotelDetailsView.as_view(), name = 'Details'),
    path('hotels/bookings/<slug:id>', views.HotelBookingListView.as_view(), name = 'Bookings'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('person.urls')),
    path('', include('hotels.urls')),
    path('booking/', include('booking.urls')),
    path('', include('buses.urls')),
]

server/booking/forms.py
from django import forms
from database import utils, models
from django.utils.crypto import get_random_string

class DeleteBookingForm(forms.Form):
    password = forms.CharField(required = True, max_length = 100)

server/booking/views.py
from django.shortcuts import render, redirect, reverse
from urllib.parse import quote, unquote
from django.views import View
from database import utils, models
from accounts.authentication import is_authenticated, get_type
from django.contrib.auth.hashers import make_password, check_password
from . import forms
import datetime

class UpcomingView(View):

    template_name = 'booking/upcoming_hotels.html'
    template_name_1 = 'booking/upcoming_buses.html'

    def get(self, request):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            if request.GET.get('type') != 'buses':
                hotel_bookings = utils.get_hotel_booking_by_user(request.session.get('email'))
                upcoming_bookings = []
                for booking in hotel_bookings:
                    date = datetime.datetime.strptime(booking.get('in_date'), "%Y-%m-%d").date()
                    if date < datetime.date.today():
                        continue
                    else:
                        hotel_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': hotel_detail.name})
                        upcoming_bookings.append(booking)
                return render(request, self.template_name, {'hotel_bookings': upcoming_bookings, 'type': get_type(request)})
            else:
                bus_bookings = utils.get_bus_booking_by_user(request.session.get('email'))
                upcoming_bookings = []
                for booking in bus_bookings:
                    date = datetime.datetime.strptime(booking.get('TravelDate'), "%Y-%m-%d").date()
                    if date < datetime.date.today():
                        continue
                    else:
                        bus_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': bus_detail.name})
                        upcoming_bookings.append(booking)
                return render(request, self.template_name_1, {'bus_bookings': upcoming_bookings, 'type': get_type(request)})

class PastView(View):

    template_name = 'booking/past_hotels.html'
    template_name_1 = 'booking/past_buses.html'

    def get(self, request):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            if request.GET.get('type') != 'buses':
                hotel_bookings = utils.get_hotel_booking_by_user(request.session.get('email'))
                past_bookings = []
                for booking in hotel_bookings:
                    date = datetime.datetime.strptime(booking.get('in_date'), "%Y-%m-%d").date()
                    if date >= datetime.date.today():
                        continue
                    else:
                        hotel_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': hotel_detail.name})
                        past_bookings.append(booking)
                return render(request, self.template_name, {'hotel_bookings': past_bookings, 'type': get_type(request)})
            else:
                bus_bookings = utils.get_bus_booking_by_user(request.session.get('email'))
                upcoming_bookings = []
                for booking in bus_bookings:
                    date = datetime.datetime.strptime(booking.get('TravelDate'), "%Y-%m-%d").date()
                    if date >= datetime.date.today():
                        continue
                    else:
                        bus_detail = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                        booking.update({'service_name': bus_detail.name})
                        upcoming_bookings.append(booking)
                return render(request, self.template_name_1, {'bus_bookings': upcoming_bookings, 'type': get_type(request)})



class BookingDetailView(View):

    template_name = 'booking/details.html'
    template_name_1 = 'booking/details_bus.html'

    def get(self, request, id):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            form = forms.DeleteBookingForm()
            if id[0] == 'H':
                booking_details = models.BookingMetaData.objects.filter(id=id)
                if not booking_details:
                    print('NOT FOUND')
                else:
                    try:
                        booking = utils.get_hotel_booking_by_id_rep(id)
                        in_date = datetime.datetime.strptime(booking.get('in_date'), "%Y-%m-%d").date()
                        cancel_option = datetime.date.today() < in_date
                        if booking.get('email') != request.session.get('email'):
                            print('NOT FOUND')
                        else:
                            hotel = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                            return render(request, self.template_name, {'form': form, 'booking': booking, 'hotel': hotel, 'cancel_option': cancel_option, 'type': get_type(request)})
                    except:
                        print('INTERNAL ERROR')
            else:
                booking_details = models.BookingMetaData.objects.filter(id=id)
                if not booking_details:
                    print('NOT FOUND')
                else:
                    try:
                        booking = utils.get_bus_booking_by_id(id)
                        TravelDate = datetime.datetime.strptime(booking.get('TravelDate'), "%Y-%m-%d").date()
                        cancel_option = datetime.date.today() < TravelDate
                        if booking.get('email') != request.session.get('email'):
                            print('NOT FOUND')
                        else:
                            bus = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                            return render(request, self.template_name_1, {'form': form, 'booking': booking, 'bus': bus, 'cancel_option': cancel_option, 'type': get_type(request)})
                    except:
                        print('INTERNAL ERROR')

    def post(self, request, id):
        userInfo = models.UserMetaData.objects.get(email = request.session.get('email'))
        if id[0] == 'H':
            booking = utils.get_hotel_booking_by_id_rep(id)
            in_date = datetime.datetime.strptime(booking.get('in_date'), "%Y-%m-%d").date()
            cancel_option = datetime.date.today() < in_date
            if cancel_option == False:
                return redirect('booking:Detail', id = id)
            else:
                hotel = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                form = forms.DeleteBookingForm(request.POST)
                if form.is_valid():
                    user = utils.get_user_rep(userInfo)
                    if check_password(form.cleaned_data.get('password'), user.get('password')) == True:
                        r = utils.delete_hotel_booking_rep(id)
                        if r == 200:
                            return redirect('person:Dashboard')
                        else:
                            return render(request, self.template_name, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Network Error', 'booking': booking, 'cancel_option': cancel_option, 'hotel': hotel, 'type': get_type(request)})
                    else:
                        return render(request, self.template_name, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Incorrect Password', 'booking': booking, 'cancel_option': cancel_option, 'hotel': hotel, 'type': get_type(request)})
                else:
                    return render(request, self.template_name, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Fields cannot be empty', 'cancel_option': cancel_option, 'booking': booking, 'hotel': hotel, 'type': get_type(request)})

        else:
            booking = utils.get_bus_booking_by_id(id)
            TravelDate = datetime.datetime.strptime(booking.get('TravelDate'), "%Y-%m-%d").date()
            cancel_option = datetime.date.today() < TravelDate
            if cancel_option == False:
                return redirect('booking:Detail', id = id)
            else:
                bus = models.ServiceMetaData.objects.get(id = booking.get('service_id'))
                form = forms.DeleteBookingForm(request.POST)
                if form.is_valid():
                    user = utils.get_user_rep(userInfo)
                    if check_password(form.cleaned_data.get('password'), user.get('password')) == True:
                        r = utils.delete_bus_booking(id)
                        if r == 200:
                            return redirect('person:Dashboard')
                        else:
                            return render(request, self.template_name_1, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Internal Error! Try again after some time.', 'booking': booking, 'cancel_option': cancel_option, 'bus': bus, 'type': get_type(request)})
                    else:
                        return render(request, self.template_name_1, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Incorrect Password', 'booking': booking, 'cancel_option': cancel_option, 'bus': bus, 'type': get_type(request)})
                else:
                    return render(request, self.template_name_1, {'form': forms.DeleteBookingForm(), 'error': '1', 'msg': 'Fields cannot be empty', 'cancel_option': cancel_option, 'booking': booking, 'bus': bus, 'type': get_type(request)})

server/booking/templates/booking/past_buses.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Past Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">PAST TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Past' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Past' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}">Upcoming Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Bus Bookings</div>

                    {% if bus_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for booking in bus_bookings %}
                    <form class="box">
                        <div class="field is-horizontal">

                            <div class="field-body">
                                <div class="field">
                                    <div class="subtitle is-5">
                                        <a href="{% url 'buses:Details' id=booking.service_id %}">{{ booking.service_name }}</a>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="subtitle is-5">
                                        <span class="tag is-medium">{{ booking.seats }} seats</span>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="subtitle is-5">
                                        <span class="tag is-medium">{{ booking.From }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ booking.To }}</span>
                                    </div>
                                </div>
                                <div class="field">
                                    <div class="subtitle is-5">
                                        <span class="tag is-medium">{{ booking.TravelDate }}</span>
                                    </div>
                                </div>
                                <div class="field">
                                    <a class="button is-rounded" href="{% url 'booking:Detail' id=booking.id %}">
                                        Booking Details
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}

server/booking/templates/booking/past_hotels.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Past Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">PAST TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Past' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Past' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}">Upcoming Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Hotel Bookings</div>

                    {% if hotel_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for hotel in hotel_bookings %}
                        <form class="box">
                            <div class="field is-horizontal">

                                <div class="field-body">
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <a href="{% url 'hotels:Details' id=hotel.service_id %}">{{ hotel.service_name }}</a>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ hotel.rooms }} rooms</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ hotel.in_date }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ hotel.out_date }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-rounded" href="{% url 'booking:Detail' id=hotel.id %}">
                                            Booking Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}

server/booking/templates/booking/upcoming_buses.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Upcoming Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">UPCOMING TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Upcoming' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Past' %}">Past Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Bus Bookings</div>

                    {% if bus_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for booking in bus_bookings %}
                        <form class="box">
                            <div class="field is-horizontal">

                                <div class="field-body">
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <a href="{% url 'buses:Details' id=booking.service_id %}">{{ booking.service_name }}</a>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ booking.seats }} seats</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ booking.From }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ booking.To }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ booking.TravelDate }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-rounded" href="{% url 'booking:Detail' id=booking.id %}">
                                            Booking Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}

server/booking/templates/booking/upcoming_hotels.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Upcoming Trips{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">UPCOMING TRIPS</h3>

        <div class="tabs">
            <div class="container">
              <ul>
                <li><a href="{% url 'booking:Upcoming' %}?type=hotels">Hotel Bookings</a></li>
                <li><a href="{% url 'booking:Upcoming' %}?type=buses">Bus Bookings</a></li>
              </ul>
            </div>
            <div class="is-right">
              <ul>
                <li><a href="{% url 'booking:Past' %}">Past Trips</a></li>
              </ul>
            </div>
        </div>

            <div class="columns">
                <div class="column section">
                    <div class="subtitle is-5">Hotel Bookings</div>

                    {% if hotel_bookings|length == 0 %}
                    <div class="section notification is-light">
                        NO BOOKINGS TO SHOW
                    </div>
                    {% endif %}

                    {% for hotel in hotel_bookings %}
                        <form class="box">
                            <div class="field is-horizontal">

                                <div class="field-body">
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <a href="{% url 'hotels:Details' id=hotel.service_id %}">{{ hotel.service_name }}</a>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ hotel.rooms }} rooms</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <div class="subtitle is-5">
                                            <span class="tag is-medium">{{ hotel.in_date }}</span> &nbsp; to &nbsp; <span class="tag is-medium">{{ hotel.out_date }}</span>
                                        </div>
                                    </div>
                                    <div class="field">
                                        <a class="button is-rounded" href="{% url 'booking:Detail' id=hotel.id %}">
                                            Booking Details
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}