server/buses/urls.py
from django.urls import path
from . import views

app_name = 'buses'

urlpatterns = [

    path('buses', views.BusSearchView.as_view(), name = 'Search'),
    path('buses/list', views.BusDisplayView.as_view(), name = 'Display'),
    path('buses/view/<slug:id>', views.BusDetailsView.as_view(), name = 'Details'),
    path('buses/bookings/<slug:id>', views.BusBookingListView.as_view(), name = 'Bookings'),

]

server/hotels/urls.py
from django.urls import path
from . import views

app_name = 'hotels'

urlpatterns = [

    path('hotels', views.HotelSearchView.as_view(), name = 'Search'),
    path('hotels/list', views.HotelDisplayView.as_view(), name = 'Display'),
    path('hotels/view/<slug:id>', views.HotelDetailsView.as_view(), name = 'Details'),
    path('hotels/bookings/<slug:id>', views.HotelBookingListView.as_view(), name = 'Bookings'),

]

server/person/urls.py
from django.urls import path
from . import views

app_name = 'person'

urlpatterns = [

    path('dashboard', views.DashboardView.as_view(), name = 'Dashboard'),
    path('manage', views.AdminView.as_view(), name = 'Admin'),
    path('logout', views.LogoutView.as_view(), name = 'Logout'),
    path('services', views.ServiceView.as_view(), name = 'Services'),
    path('service/<slug:id>', views.EditServiceView.as_view(), name = 'EditService'),
    path('delete_manager_from_service/<slug:id>/<slug:email>', views.DeleteManagerView.as_view(), name = 'DeleteManager'),
    path('delete_bus_route/<slug:id>/<int:index>', views.DeleteRouteView.as_view(), name = 'DeleteBusRoute'),

]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('person.urls')),
    path('', include('hotels.urls')),
    path('booking/', include('booking.urls')),
    path('', include('buses.urls')),
]

server/person/forms.py
from django import forms
from database import utils, models
from django.utils.crypto import get_random_string

class UserPrivilageForm(forms.Form):
    CHOICES = ( ('U', 'Standard User'),
                ('A', 'Admin'),
                ('S', 'Service Provider'),)
    email = forms.EmailField(max_length = 100, required = True)
    privilage = forms.ChoiceField(choices = CHOICES, widget = forms.Select)

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def clean_privilage(self):
        privilage = self.cleaned_data['privilage']
        email = self.cleaned_data['email']
        user = self.get_object(email)
        if user.count() > 0:
            user = user[0]
            utils.check_primary(user)
            r = utils.update_user_rep(user, type = privilage)
            if r == 200:
                return privilage
            else:
                raise forms.ValidationError('Network Error')
        else:
            raise forms.ValidationError('User not found')

class PasswordForm(forms.Form):
    password = forms.CharField(required = True, max_length = 100)

class ManagersForm(forms.Form):
    email = forms.EmailField(max_length = 100, required = True)

    def get_object(self, email):
        return models.UserMetaData.objects.filter(email = email)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user = self.get_object(email)
        if user.count() > 0:
            user = user[0]
            user = utils.get_user_rep(user)
            if user.get('type') == 'S':
                return email
            else:
                raise forms.ValidationError('User not a service provider')
        else:
            raise forms.ValidationError('User does not exist')


class NewServiceForm(forms.Form):
    CHOICES = ( ('B', 'Bus Service'),
                ('H', 'Hotel Service'),)
    name = forms.CharField(max_length = 100, required = True)
    service_type = forms.ChoiceField(choices = CHOICES, widget = forms.Select)

class EditBusServiceForm(forms.Form):
    CHOICES = ( ('B', 'Bus Service'),
                ('H', 'Hotel Service'),)
    id = forms.CharField(max_length = 100, required = True, widget = forms.TextInput(attrs={'readonly': True}))
    name = forms.CharField(max_length = 100, required = True)
    service_type = forms.CharField(widget = forms.TextInput(attrs={'readonly': True}))
    bus_number = forms.CharField(max_length = 20, required = True)
    seats = forms.IntegerField(required = True)
    price = forms.IntegerField(required = True)
    is_ready = forms.BooleanField(required = False)

class EditRouteForm(forms.Form):
    stop_name = forms.CharField(max_length = 100, required = True)
    day = forms.IntegerField(min_value = 0, required = True)
    time_hour = forms.IntegerField(min_value = 0, max_value = 23, required = True)
    time_mins = forms.IntegerField(min_value = 0, max_value = 59, required = True)
    boarding_point = forms.CharField(max_length = 100, required = True)

class EditHotelServiceForm(forms.Form):
    CHOICES = ( ('B', 'Bus Service'),
                ('H', 'Hotel Service'),)
    id = forms.CharField(max_length = 100, required = True, widget = forms.TextInput(attrs={'readonly': True}))
    name = forms.CharField(max_length = 100, required = True)
    service_type = forms.CharField(widget = forms.TextInput(attrs={'readonly': True}))
    city = forms.CharField(max_length = 100, required = True)
    area = forms.CharField(max_length = 100, required = True)
    address = forms.CharField(max_length = 200, required = True)
    description = forms.CharField(required = True, widget = forms.Textarea)
    rooms = forms.IntegerField(required = True)
    price = forms.IntegerField(required = True)
    is_ready = forms.BooleanField(required = False)
    check_in = forms.TimeField(required = True)
    check_out = forms.TimeField(required = True)

class HeartBeatForm(forms.Form):
    rate = forms.IntegerField()

server/person/views.py
from django.shortcuts import render, redirect
from django.views import View
from database import utils, models
from accounts.authentication import is_authenticated, get_type
from django.contrib.auth.hashers import make_password, check_password
from . import forms
from django.utils.crypto import get_random_string

class DashboardView(View):
    template_name = 'person/dashboard.html'

    def get(self, request):
        if is_authenticated(request) == None:
            return redirect('accounts:Login')
        else:
            services = models.ServiceMetaData.objects.all().count()
            bookings = models.BookingMetaData.objects.all().count()
            users = models.UserMetaData.objects.all().count()
            return render(request, self.template_name, {'type': get_type(request), 'users': users, 'bookings': bookings, 'services': services})

class AdminView(View):
    template_name = 'person/admin.html'

    def check_status(self):
        return utils.check_status()

    def get(self, request):
        if is_authenticated(request) != None and get_type(request) == 'A':
            form1 = forms.UserPrivilageForm()
            hb_rate = models.HeartBeatRate.objects.all()[0].rate
            form2 = forms.HeartBeatForm(initial = {'rate': hb_rate})
            dbs = models.DatabaseDetails.objects.order_by('name')
            return render(request, self.template_name, {'form1': form1, 'form2': form2, 'dbs': dbs, 'type': get_type(request)})
        else:
            return redirect('accounts:Login')

    def post(self, request):
        hb_rate = models.HeartBeatRate.objects.all()[0].rate
        form2 = forms.HeartBeatForm(initial = {'rate': hb_rate})
        form1 = forms.UserPrivilageForm()
        dbs = models.DatabaseDetails.objects.order_by('name')
        if 'user_privilage' in request.POST:
            form1 = forms.UserPrivilageForm(request.POST)
            if form1.is_valid():
                return render(request, self.template_name, {'form1': forms.UserPrivilageForm(), 'form2': form2, 'dbs': dbs, 'type': get_type(request), 'success1': '1', 'msg1': 'Request Processed'})
            else:
                return render(request, self.template_name, {'form1': form1, 'form2': form2, 'dbs': dbs, 'type': get_type(request), 'error1': '1'})
        elif 'database_edit' in request.POST:
            db = models.DatabaseDetails.objects.filter(name = request.POST.get('name'))[0]
            db.ip_addr = request.POST.get('ip_addr')
            db.port = request.POST.get('port')
            db.save()
            utils.update_database_status()
            return redirect('person:Admin')
        elif 'heart_beat' in request.POST:
            metaData = models.HeartBeatRate.objects.all()[0]
            metaData.rate = int(request.POST.get('rate'))
            metaData.save()
            return redirect('person:Admin')

class ServiceView(View):
    template_name = 'person/services.html'

    def get_object(self, email):
        return models.ServiceMetaData.objects.filter(provider__contains=list([email]))

    def get(self, request):
        if is_authenticated(request) != None:
            if get_type(request) == 'S':
                bus_services, hotel_services = utils.get_services_by_email_rep(request.session.get('email'))
                form = forms.NewServiceForm()
                return render(request, self.template_name, {'form': form, 'services': bus_services, 'services1': hotel_services, 'type': get_type(request)})
            else:
                return redirect('person:Dashboard')
        else:
            return redirect('accounts:Login')

    def post(self, request):
        services, services1 = utils.get_services_by_email_rep(request.session.get('email'))
        if 'new_service' in request.POST and request.POST.get('service_type') == 'B':
            form = forms.NewServiceForm(request.POST)
            if form.is_valid():
                id = 'B' + get_random_string(15)
                while utils.check_service_id(id) == False:
                    id = 'B' + get_random_string(15)
                provider = request.session.get('email')
                r = utils.insert_bus_service_rep(id, form.cleaned_data.get('name'), provider)
                if r == 201:
                    return redirect('person:EditService', id = id)
                else:
                    return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Network Error'})
            else:
                return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Invalid Details'})
        elif 'new_service' in request.POST and request.POST.get('service_type') == 'H':
            form = forms.NewServiceForm(request.POST)
            if form.is_valid():
                id = 'H' + get_random_string(15)
                while utils.check_service_id(id) == False:
                    id = 'H' + get_random_string(15)
                provider = request.session.get('email')
                r = utils.insert_hotel_service_rep(id, form.cleaned_data.get('name'), provider)
                if r == 201:
                    return redirect('person:EditService', id = id)
                else:
                    return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Error: Enough Replicas not created!'})
            else:
                return render(request, self.template_name, {'form': form, 'services': services, 'services1': services1, 'type': get_type(request), 'error': '1', 'msg': 'Invalid Details'})


class EditServiceView(View):
    template_name = 'person/bus_service_edit.html'
    template_name_1 = 'person/hotel_service_edit.html'

    def get_object(self, id):
        return models.ServiceMetaData.objects.filter(id = id)

    def get_user(self, email):
        user = models.UserMetaData.objects.filter(email = email)
        user = user[0]
        return utils.get_user_rep(user)

    def get_form(self, id):
        S = utils.get_bus_service_by_id_rep(id)
        form = forms.EditBusServiceForm(initial = {'id': id, 'service_type': 'Bus', 'name': S.get('name'), 'bus_number': S.get('bus_number'), 'seats': S.get('seats'), 'price': S.get('price'), 'is_ready': S.get('is_ready')})
        return form

    def get_form_1(self, id):
        S = utils.get_hotel_service_by_id_rep(id)
        form = forms.EditHotelServiceForm(initial = {'id': id, 'service_type': 'Hotel', 'name': S.get('name'), 'description': S.get('description'), 'city': S.get('city'), 'address': S.get('address'), 'area': S.get('area'), 'rooms': S.get('rooms'), 'check_in': S.get('check_in'), 'check_out': S.get('check_out'), 'price': S.get('price'), 'is_ready': S.get('is_ready')})
        return form

    def get_service(self, id):
        S = utils.get_bus_service_by_id_rep(id)
        S.update({'combined_list': zip(S.get('route'), S.get('timing'), S.get('boarding_point'))})
        return S

    def get_service_1(self, id):
        S = utils.get_hotel_service_by_id_rep(id)
        return S

    def get(self, request, id):
        if is_authenticated(request) != None:
            service = self.get_object(id)
            if service.count() > 0:
                service = service[0]
                if service.type == 'B':
                    email = request.session.get('email')
                    if email in service.provider:
                        form = self.get_form(id)
                        form1 = forms.ManagersForm()
                        form2 = forms.PasswordForm()
                        form3 = forms.EditRouteForm()
                        return render(request, self.template_name, {'form': form, 'form1': form1, 'form2': form2, 'form3': form3, 'service': self.get_service(id), 'type': get_type(request)})
                    else:
                        print('NOT FOUND')

                elif service.type == 'H':
                    email = request.session.get('email')
                    if email in service.provider:
                        form1 = forms.ManagersForm()
                        form2 = forms.PasswordForm()
                        return render(request, self.template_name_1, {'form': self.get_form_1(id), 'form1': form1, 'form2': form2, 'service': self.get_service_1(id), 'type': get_type(request)})

            else:
                print('NOT FOUND')
        else:
            return redirect('person:Dashboard')

    def post(self, request, id):
        service = self.get_object(id)
        service = service[0]
        if service.type == 'B':
            if 'delete_service' in request.POST:
                user = self.get_user(request.session.get('email'))
                if check_password(request.POST.get('password'), user.get('password')):
                    r = utils.delete_bus_service_rep(id = id)
                    if r == 200:
                        return redirect('person:Services')
                    else:
                        return render(request, self.template_name, {'form': self.get_form(id), 'form1': forms.ManagersForm(), 'form2': forms.PasswordForm(), 'form3': forms.EditRouteForm(), 'error2': '1', 'msg2': 'Network Error', 'service': self.get_service(id), 'type': get_type(request)})
                else:
                    return render(request, self.template_name, {'form': self.get_form(id), 'form1': forms.ManagersForm(), 'form2': forms.PasswordForm(), 'form3': forms.EditRouteForm(), 'error2': '1', 'msg2': 'Incorrect Password', 'service': self.get_service(id), 'type': get_type(request)})
            elif 'add_manager' in request.POST:
                form1 = forms.ManagersForm(request.POST)
                if form1.is_valid():
                    email = form1.cleaned_data.get('email')
                    if email not in service.provider:

server/person/templates/person/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title_block %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bulma.css' %}">
  </head>
  <body>
      <!-- NAVBAR -->
      <nav class="navbar is-light" role="navigation" aria-label="main navigation">
          <div class="container">
              <div class="navbar-brand">
                  <a class="navbar-item" href="https://bulma.io">
                      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
                  </a>
                  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                  </a>
              </div>
              <div id="navbarBasicExample" class="navbar-menu">
                  <div class="navbar-start">
                      <a class="navbar-item" href="{% url 'person:Dashboard' %}">
                          <p style="margin: 10px; font-size: 18px;">Dashboard</p>
                      </a>
                      <a class="navbar-item">
                          <p style="margin: 10px; font-size: 18px;">Hotels</p>
                      </a>
                      <a class="navbar-item">
                          <p style="margin: 10px; font-size: 18px;">Buses</p>
                      </a>
                  </div>
                  <div class="navbar-end">
                      <a class="navbar-item" href="{% url 'person:Admin' %}" {% block admin_block %}{% endblock %}>
                          <p style="margin: 10px; font-size: 18px;">Admin</p>
                      </a>
                      <a class="navbar-item" href="{% url 'person:Services' %}" {% block service_block %}{% endblock %}>
                          <p style="margin: 10px; font-size: 18px;">Services</p>
                      </a>
                      <a class="navbar-item">
                          <p style="margin: 10px; font-size: 18px;">Account</p>
                      </a>
                      <a class="navbar-item" href="{% url 'person:Logout' %}">
                          <p style="margin: 10px; font-size: 18px;">Logout</p>
                      </a>
                  </div>
              </div>
          </div>
     </nav>
     <!-- NAVBAR END -->
     <section class="section">
         <div class="container">
             {% block content_block %}{% endblock %}
         </div>
     </section>
  </body>
</html>

server/person/templates/person/dashboard.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Dashboard{% endblock %}

{% block content_block %}

    <div class="container has-text-centered">

        <h3 class="subtitle is-4">PLAN YOUR TRIP</h3>
        <div class="columns">
            <div class="column">
                <div class="box">
                    <div class="heading" style="font-size: 18px;">Easy<span style="color: green">Travels</span> Hotels</div>
                    <section class="section"><a href="{% url 'hotels:Search' %}" class="button">Book Now</a></section>
                </div>
            </div>
            <div class="column">
                <div class="box">
                    <div class="heading" style="font-size: 18px;">Easy<span style="color: green">Travels</span> Buses</div>
                    <section class="section"><a href={% url 'buses:Search' %} class="button">Book Now</a></section>
                </div>
            </div>
        </div>

        <div class="section">
            <h3 class="subtitle is-5">Why Choose <p style="font-size: 34px;">Easy<span style="color: green;">Travels</span></p></h3>
            <div class="section box">
                <div class="columns">

                    <div class="column"><span style="font-size: 40px; color: blue;">{{ users }}</span> <div class="heading" style="font-size: 18px;"> Registered Users </div></div>
                    <div class="column"><span style="font-size: 40px; color: red;">{{ bookings }}</span> <div class="heading" style="font-size: 18px;"> Successful Bookings </div></div>
                    <div class="column"><span style="font-size: 40px; color: green;">{{ services }}</span> <div class="heading" style="font-size: 18px;"> Services </div></div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

server/person/templates/person/services.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block service_block %}{% if type != 'S' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}
{% block admin_block %}{% if type != 'A' %}style="visibilty: hidden; display: none;"{% endif %}{% endblock %}

{% block title_block %}Services{% endblock %}

{% block content_block %}

    <div class="columns has-text-centered">
        <div class="column is-4 is-offset-4">
            <div class="box">
                <h3 class="subtitle is-5">New Service</h3>
                <form class="section" method = "POST">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                            {% render_field form.name type="text" class="input" placeholder="Service Name" %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <div class="select is-fullwidth">
                                <select name="service_type" id="id_service_type">
                                    {% for x, y in form.fields.service_type.choices %}
                                        <option value="{{ x }}">{{ y }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <button name="new_service" class="button is-fullwidth is-primary">Confirm</button>
                </form>

                <!-- MESSAGES -->

                <div class="tag is-medium">
                    {% if error %}
                        <div>
                            <div class="content">
                                <p style="color: red;">{{ msg }}</p>
                            </div>
                        </div>
                    {% else %}
                        <div>
                            <div class="content">
                                <p style="color: blue;">Start a new service</p>
                            </div>
                        </div>
                    {% endif %}
                </div>

                <!-- END MESSAGES -->
            </div>
        </div>
    </div>
    {% if services|length > 0 %}
    <div class="columns has-text-centered">
        <div class="column">
            <div class="box">
                <h3 class="subtitle is-5">Your Bus Services</h3>
                <div>
                    <table class="table is-fullwidth">
                        <thead>
                            <tr>
                              <th><abbr title="Number">Sr. No.</abbr></th>
                              <th>Name</th>
                              <th>Bus Number</th>
                              <th>Source</th>
                              <th>Destination</th>
                              <th>Departure</th>
                              <th>Arrival</th>
                              <th>Capacity</th>
                              <th></th>
                              <th>Status</th>
                            </tr>
                      </thead>
                      <tbody>
                          {% for service in services %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'person:EditService' id=service.id %}">{{ service.name }}</a></td>
                                <td>{% if service.bus_number != '' %}{{ service.bus_number }}{% else %}-{% endif %}</td>
                                <td>{% if service.route|length > 1 %}{{service.route.0}}{% else %}-{% endif %}</td>
                                <td>{% if service.route|length > 1 %}{% for route in service.route %}
                                                                        {% if forloop.last %}{{route}}{% endif %}
                                                                    {% endfor %}{% else %}-{% endif %}
                                </td>
                                <td>{% if service.timing|length > 1 %}{{service.timing.0}}{% else %}-{% endif %}</td>
                                <td>{% if service.timing|length > 1 %}{% for timing in service.timing %}
                                                                        {% if forloop.last %}{{timing}}{% endif %}
                                                                    {% endfor %}{% else %}-{% endif %}</td>
                                <td>{{ service.seats }}</td>
                                <td><a href="{% url 'buses:Bookings' id=service.id %}">View Bookings</a></td>
                                <td>{% if service.is_ready == False %}<span style="color: red;">INACTIVE</span>{% else %}<span style="color: green;">RUNNING</span>{% endif %}</td>
                            <tr>
                          {% endfor %}
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="columns has-text-centered">
        <div class="column is-4 is-offset-4">
            <div class="box">
                <div class="message">
                    You do not manage any bus services
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% if services1|length > 0 %}
    <div class="columns has-text-centered">
        <div class="column">
            <div class="box">
                <h3 class="subtitle is-5">Your Hotel Services</h3>
                <div>
                <table class="table is-fullwidth">
                    <thead>
                        <tr>
                          <th><abbr title="Number">Sr. No.</abbr></th>
                          <th>Name</th>
                          <th>City</th>
                          <th>Area</th>
                          <th>Rooms</th>
                          <th></th>
                          <th>Status</th>
                        </tr>
                  </thead>
                  <tbody>
                      {% for service in services1 %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'person:EditService' id=service.id %}">{{ service.name }}</a></td>
                            <td>{% if service.city != '' %}{{ service.city }}{% else %}-{% endif %}</td>
                            <td>{% if service.area != '' %}{{ service.area }}{% else %}-{% endif %}</td>
                            <td>{% if service.rooms != '' %}{{ service.rooms }}{% else %}-{% endif %}</td>
                            <td><a href="{% url 'hotels:Bookings' id=service.id %}">View Bookings</a></td>
                            <td>{% if service.is_ready == False %}<span style="color: red;">INACTIVE</span>{% else %}<span style="color: green;">RUNNING</span>{% endif %}</td>
                        <tr>
                      {% endfor %}
                  </tbody>
                </table>
            </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="columns has-text-centered">
        <div class="column is-4 is-offset-4">
            <div class="box">
                <div class="notification is-light">
                    You do not manage any hotel services
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}